---
- name: be sure rabbitmq official repo is used.
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present
- name: be sure official repo has its key installed.
  apt_key: url='https://www.rabbitmq.com/rabbitmq-signing-key-public.asc' state=present
- name: install rabbitMQ
  apt: pkg=rabbitmq-server state=installed update_cache=yes
- name: enable management console
  command: rabbitmq-plugins enable rabbitmq_management
- name: check if admin user was previously added
  shell: rabbitmqctl list_users | grep "^admin"
  register: admin_user_check
  ignore_errors: true

- name: add admin user
  command: rabbitmqctl add_user admin password
  when: admin_user_check|failed
- name: set admin user as administrator
  command: rabbitmqctl set_user_tags admin administrator
  when: admin_user_check|failed
- name: set permissions for admin user
  command: rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
  when: admin_user_check|failed

- name: ensure lines in hosts file are preseqnt
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
      - { regexp: '^192\.168\.1\.3', line: '192.168.1.3 r2d2' }
      - { regexp: '^192\.168\.1\.4', line: '192.168.1.4 c3po' }
      - { regexp: '^192\.168\.1\.10', line: '192.168.1.10 gonk' }

- name: ensure same erlang cookie across nodes
  copy: src=../files/erlang.cookie dest=/var/lib/rabbitmq/.erlang.cookie owner=rabbitmq group=rabbitmq mode=0400
